flowchart TD
    U1[UOB1: Пользователь авторизован]
    U2[UOB2: Открытие корзины]
    U3[UOB3: Проверка содержимого корзины]
    U4[UOB4: Нажатие \"Оформить заказ\"]
    U5[UOB5: Ввод адреса и способа оплаты]
    U6[UOB6: Подтверждение оформления заказа]
    U7[UOB7: Проверка наличия товаров]
    XOR1{Товары в наличии?}
    U7a[UOB7a: Ошибка - недостаточно товара]
    U8[UOB8: Сохранение заказа в БД]
    U9[UOB9: Очистка корзины]
    U10[UOB10: Уведомление пользователя]
    U11[UOB11: Завершение процесса]

    U1 --> U2
    U2 --> U3
    U3 --> U4
    U4 --> U5
    U5 --> U6
    U6 --> U7
    U7 --> XOR1

    XOR1 -- Да --> U8
    XOR1 -- Нет --> U7a
    U7a --> U3

    U8 --> U9
    U9 --> U10
    U10 --> U11
